version: '3'

services:
  web:
    image: 'php:7.2-apache'
    container_name: php
    restart: always
    ports:
      - '80:80'
    command: |
      sh -c 'a2enmod rewrite \
          && echo "memory_limit = 512M" >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini \
          && apache2-foreground'
    volumes:
      - .:/var/www/html
    environment:
      - ALLOW_OVERRIDE=true
